language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: FZrzXHyle2N7Sy3BCGTM4ONFPxWXZF1yG/F7kWVAMogzqtJ/URFhwkbCk4FT/s1awsTLX4augf3vClu3onf/HoyXnm30zK3hQ1hxKa4y8gZ6GNBDuCLNAjC6YXzJgkZCCKbAbJqwAOeLJzNXxBflgagxlUkw5PSE3yRl1aOa17c0VOa7fpKZ7LUjF6X8q8jlHGIFTyWU6oaqxttPMPyFRFb/4FsyJbrC6ZcYopi65DWjgAcXccL3SCsJrSUwg5D34IxVOxw5zrm1+YOZpTAEEej9yyXm2eki7FEzBWU9lA+BLu4lL9QiPx15di6iJX1UWLgI5Mt1q66OX17WTRd6om/muoavG96bJYShd6wCzKOcnn9zuvz9MnndfbQ/P7PS0K4jHi3hM2VCdnHvEdluBGi7FHnE27YQY5bsK7oqr4QBRyy0uLe8XTlpT80GoqkhWvnAlNU5tAUaEpGv33byTUq/FcV/VOt8qp0DFAypqiXqrStPq+syelR140i7P6D4InbryVWzJ22twyyPYc/YphVcIXxr5AMNHW7nHx0EIIS+D3jArGhathK1B53sYe0GmwHlbAF9ratAIH7UJogDW8DL0ocTl7VaRe7V7KFoymXnVvT7xV7EDmR1jpe8jY/wTHZaEU4M6XIp6qTZxnBEEuhDai8H0QoJBzf9cnFIRsY=
  app: devops-pipeline-biridin
  edge: true
